### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by mefest** [mefest/QNotepad#2]
dont work

**Comment by Racc-oon** [comment]
@mefest 10/10 commit

**Comment by UjGamer** [comment]
Прошу не засорять багтрекер.

**Comment by mefest** [comment]
dont work!!!!

**Comment by mefest** [comment]
![image](https://cloud.githubusercontent.com/assets/3998442/17852081/5d4b4136-6876-11e6-90cc-2119c6639e0b.png)

**Comment by mefest** [comment]
заполните багтрекер!
