### ISSUE TITLE
Отсутствует вытеснение старых записей в "Последних файлах"

### ISSUE THREAD

**Issue by UjGamer** [mefest/QNotepad#4]
### **Ошибка**
При полном заполнении списка последних файлов, они перестают добавлятся.

### **Ожидаемое поведение**
Самая старая запись (5) должна отбрасываться, а в начало(1) должна добавляться новая.

**Comment by mefest** [comment]
Исправил в коммите https://github.com/mefest/QNotepad/commit/0828ca3a33b1d5508ee74840b909199dd09dae3b
