### ISSUE TITLE
Падение программы при закрытии вкладки с только что, сохранённым под другим именем, файлом.

### ISSUE THREAD

**Issue by UjGamer** [mefest/QNotepad#6]
## **Ошибка**
Проваливается проверка на нулевой указатель в m_currentEditor при смене вкладки.
``ASSERT: "m_currentEditor != nullptr" in file ../QNotepad/mainwindow.cpp, line 366``

## **Воспроизведение**

1. Открыть файл
2. Сохранить его под другим именем через ``Сохранить Как``
3. Закрыть все вкладки.

## **Примечания/Исследование**

- Вероятно указатель становится нулевым при удалении старого редактора в saveAs()
- Этот баг не появляется при выполнении тех-же действий с noname-вкладкой.

## **Предложения**

- Внести дополнителную проверку в removeEditor()
Например: Аргумент выключающий зануление m_currentEditor при закрытии последней вкладки
(этим действием вобще эта функция  не должна заниматься).

**Comment by mefest** [comment]
Неудалось возпроизвести ошибку. Возможно исправлена после мерджа.

**Comment by UjGamer** [comment]
Неисправлено.

**Comment by mefest** [comment]
Исправленно в коммите https://github.com/mefest/QNotepad/commit/091a07a7ff9a12657e629c57f8ccc7c9cb9b9afc
